

typedef void (*p_clear_screen)(void);
typedef void (*p_lir_refresh_entire_screen)(void);
typedef void (*p_lir_refresh_screen)(void);
typedef void (*p_lir_line)(int x1, int yy1, int x2,int y2, unsigned char c);
typedef void (*p_lir_hline)(int x1, int y, int x2, unsigned char c);
typedef void (*p_lir_putbox)(int x, int y, int w, int h, size_t* dp);
typedef void (*p_lir_getbox)(int x, int y, int w, int h, size_t* dp);
typedef void (*p_lir_fillbox)(int x, int y,int w, int h, unsigned char c);
typedef void (*p_lir_fix_bug)(int bug);
typedef void (*p_lir_getpalettecolor)(int j, int *r, int *g, int *b);
typedef void (*p_lir_setpixel)(int x, int y, unsigned char c);
typedef int (*p_lir_getpixel)(int x, int y);

extern p_clear_screen clear_screen;
extern p_lir_refresh_screen lir_refresh_screen;
extern p_lir_refresh_entire_screen lir_refresh_entire_screen;
extern p_lir_line lir_line;
extern p_lir_hline lir_hline;
extern p_lir_putbox lir_putbox;
extern p_lir_getbox lir_getbox;
extern p_lir_fillbox lir_fillbox;
extern p_lir_fix_bug lir_fix_bug;
extern p_lir_getpalettecolor lir_getpalettecolor;
extern p_lir_setpixel lir_setpixel;
extern p_lir_getpixel lir_getpixel;

void xclear_screen(void);
void lclear_screen(void);
void fclear_screen(void);
void xlir_refresh_entire_screen(void);
void llir_refresh_entire_screen(void);
void xlir_refresh_screen(void);
void llir_refresh_screen(void);
void llir_line(int x1, int yy1, int x2,int y2, unsigned char c);
void xlir_line(int x1, int yy1, int x2,int y2, unsigned char c);
void flir_line(int x1, int yy1, int x2,int y2, unsigned char c);
void xlir_hline(int x1, int y, int x2, unsigned char c);
void xlir_putbox(int x, int y, int w, int h, size_t* dp);
void xlir_getbox(int x, int y, int w, int h, size_t* dp);
void xlir_fillbox(int x, int y,int w, int h, unsigned char c);
void flir_hline(int x1, int y, int x2, unsigned char c);
void flir_putbox(int x, int y, int w, int h, size_t* dp);
void flir_getbox(int x, int y, int w, int h, size_t* dp);
void flir_fillbox(int x, int y,int w, int h, unsigned char c);
void llir_hline(int x1, int y, int x2, unsigned char c);
void llir_putbox(int x, int y, int w, int h, size_t* dp);
void llir_getbox(int x, int y, int w, int h, size_t* dp);
void llir_fillbox(int x, int y,int w, int h, unsigned char c);
void llir_fix_bug(int bug);
void xlir_fix_bug(int bug);
void llir_getpalettecolor(int j, int *r, int *g, int *b);
void llir_setpixel(int x, int y, unsigned char c);
void flir_getpalettecolor(int j, int *r, int *g, int *b);
void flir_setpixel(int x, int y, unsigned char c);
void xlir_getpalettecolor(int j, int *r, int *g, int *b);
void xlir_setpixel(int x, int y, unsigned char c);
int llir_getpixel(int x, int y);
int flir_getpixel(int x, int y);
